name: Deploy (production)

on:
  push:
    branches:
      - main
      - rezrah/app-github-pages # for testing

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    uses: primer/.github/.github/workflows/deploy.yml@main
    with:
      node_version: 16
      install: yarn
      build: yarn build
      output_dir: build
